AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'POST, OPTIONS'"
      AllowHeaders: "'Content-Type'"
Resources:
  CounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: counter.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /counter
            Method: post
  VisitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor-counts
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
